### ISSUE TITLE
org.json.JSONException: Value <br of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by DanielAzzam** [Zodrag/Login_and_Register#1]
hello Zodrag, 

i hope you can help me because i am in a big mess . 
i previously followed Tonikami's project step by step an reached the subject error , and then followed your steps  bu i had the same error . i cant understand the parser issue at all , i have speeding days on google to try to figure out what is the bug exactly , yet i couldn't . 
i know there is something wrong with the server requests class , specifically when assigining newData to the jObject  but i cant figure out what . 
i need your help urgently , please 

![image](https://cloud.githubusercontent.com/assets/17107884/12871957/040c2170-cd9a-11e5-835c-cf8d0f3cd0f6.png)

![image](https://cloud.githubusercontent.com/assets/17107884/12871969/ae658a94-cd9a-11e5-9f97-37d99e87f255.png)

**Comment by xprimate** [comment]
Men i am having exactly the same problem as DanielAzzam . After switching from Tonikami's code to   Zodrag because i did not want to use depreciated classes. Men you need to save our ass.
Thanks for your code.

**Comment by DanielAzzam** [comment]
Hello switch there xprimate . Check the code on . And for errors check my comment

**Comment by DanielAzzam** [comment]
http://www.androidhive.info/2011/10/android-login-and-registration-screen-design/

**Comment by xprimate** [comment]
Ok thanks i have check the website, and the code has nothing to do with database talk more of JSON. How does the example help to solve the current issue on Zodrag's code or am I missing something.

**Comment by DanielAzzam** [comment]
You need a register login application including db and php scripts . Well its all there  in the link i provided  apply the code provides by ravi and for any error refer to the comment

**Comment by xprimate** [comment]
Ok i have see the link in the comment section of the link. But men his approach is different and a little bit complex, and i have rewrite the code from scratch.

**Comment by DanielAzzam** [comment]
As you want . I tried most of the codes from scratch and found ravi's code the best . Am sorry i dont have time to gelp you woth other codes

**Comment by xprimate** [comment]
Thanks anyway. I really appreciate

**Comment by xprimate** [comment]
DanielAzzam  Men i have gone through Ravi's and it is well structured and good. But i Still get this error after trying alot of fixes:
 org.json.JSONException: Value <br of type java.lang.String cannot be converted to JSONObject
and it is pointing at this line in my code:
 pDialog.setMessage("Registering ...");
        showDialog();

```
    StringRequest strReq = new StringRequest(Method.POST,
           ** AppConfig.URL_REGISTER, new Response.Listener<String>() {**

        @Override
        public void onResponse(String response) {
            Log.d(TAG, "Register Response: " + response.toString());
            hideDialog();

            try {
                JSONObject jObj = new JSONObject(response);
                boolean error = jObj.getBoolean("error");
                if (!error) {
```

**Comment by DanielAzzam** [comment]
Bro even if it points to the java code . The error could is related to syntax .we are using sql inside java code here so any space makes differnence . For example . "Select \* from" & "users" is different from "Select \* from" & " users"  . If you got what i mean revise ur syntax .  On all ways these errors are generated while trying to isert user into sqlite db so provide more info about ur logact where it shows the log tags but please revise ur syntax firat especially if u didnt open ravi' s project and you instead did some changes to it .

**Comment by xprimate** [comment]
Thanks for your quick response. 

I have checked my syntax and actually copied and pasted Ravis code to my own code. 
this is my logcat output:

![logcat](https://cloud.githubusercontent.com/assets/17166016/13303550/619b5d06-db50-11e5-9e40-bb19f856adb5.GIF)

**Comment by xprimate** [comment]
men i can't believe how stupid i am. the problem was from my database authentication. instead of using empty string("") as my DB_PASSWORD i used "root". chrome's  postman extension was helpful

**Comment by DanielAzzam** [comment]
Good you you did it   thats coding

**Comment by xprimate** [comment]
Hi Dan. Long time no see i hope you are good.
Pls i want to also insert the "unique_id" in the "user" table to another table named my "location" with the same "unique_id" column in the same database using the same prepared statement, but it giving me the usual "org.json.JSONException: Value <br of type java.lang.String cannot be converted to JSONObject"
 I created a method called "storeUniqueId()" in the "DB_Functions.php" file and called the method in "register.php"  to do that. Pls help. my code is below
.......

// store unique_id in location table(from "DB_Function.php")
    **public function storeUniqueId()**{
         $uuid=$GLOBAL['uuid'];
        $stmt = $this->conn->prepare("INSERT INTO location(unique_id) VALUES(?, NOW())");
        $stmt->bind_param("s", $uuid);
        $stmt->execute();
        $stmt->close();
        }
    /**
     \* Storing new user
     \* returns user details
     _/  
    public function storeUser($name, $username, $email, $password) {
        $GLOBAL['uuid'] = uniqid('', true);
        $hash = $this->hashSSHA($password);
        $encrypted_password = $hash["encrypted"]; // encrypted password
        $salt = $hash["salt"]; // salt  
        $stmt = $this->conn->prepare("INSERT INTO users(unique_id, name, username, email, encrypted_password, salt, created_at) VALUES(?, ?, ?, ?, ?, ?, NOW())");
        $stmt->bind_param("ssssss", $GLOBAL['uuid'], $name, $username, $email, $encrypted_password, $salt);
        $result = $stmt->execute();
        $stmt->close();
        // check for successful store
        if ($result) {
            $stmt = $this->conn->prepare("SELECT_FROM users WHERE email = ?");
            $stmt->bind_param("s", $email);
            $stmt->execute();
            $user = $stmt->get_result()->fetch_assoc();
            $stmt->close();
            return $user;
        } else {
            return false;
        }
    }
...
//where i called the method(from "register.php")

```
// receiving the post params
$name = $_POST['name'];
$username = $_POST['username'];
$email = $_POST['email'];
$password = $_POST['password'];

// check if user is already existed with the same email
if ($db->isUserExisted($email)) {
    // user already existed
    $response["error"] = TRUE;
    $response["error_msg"] = "User already existed with " . $email;
    echo json_encode($response);
} else {
    // create a new user
    $user = $db->storeUser($name, $username, $email, $password);
   storeUniqueId();
    if($user){
```

 ...

This is my "location" table structure
![location](https://cloud.githubusercontent.com/assets/17166016/15005460/de9c8616-11bc-11e6-8a92-d706b6ad096e.GIF)

**Comment by mreesey** [comment]
@xprimate  can you elaborate more on how you solved this issue? I am facing the same issue currently. Thanks

**Comment by kudarukuni** [comment]
error resides in the php script taking values from the AppConfig.URL_REGISTER, where the SQL statement says INSERT INTO users(....) VALUES(?,?,?). Most coders try to write code in a readable way such as VALUES(?, ?, ?) which will cause the database to trip.

**Comment by xprimate** [comment]
Thank for getting back.
This is like 4 years ago, i don't even know where that piece of code is, lol
Thanks all the same.

**Comment by SuleimanSaid** [comment]
Thanks very much
